language: swift  #1
osx_image: xcode8.3 #2
xcode_project: testauto.xcodeproj #3
# cocoa pads replace xcode_project with xcode_workspace and use .xcworkspace file
xcode_scheme: testauto #4
#xcode_sdk: iphonesimulator5s #5